services:
  # K8s WebUI - Single service with embedded SPA and SQLite database
  denshimon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: denshimon
    restart: unless-stopped
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/denshimon.db
      - PASETO_SECRET_KEY=dev-32-byte-secret-key-for-prod!
      - TOKEN_DURATION=24h
      - LOG_LEVEL=debug
      - ENVIRONMENT=production
    volumes:
      - ~/.kube:/home/denshimon/.kube:ro  # Mount kubeconfig for K8s access
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker-in-Docker scenarios
      - k8s_webui_data:/app/data  # SQLite database storage
    ports:
      - "8080:8080"
    networks:
      - denshimon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  k8s_webui_data:
    name: denshimon-data

networks:
  denshimon-network:
    name: denshimon-network
    driver: bridge