version: "3.8"

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: k8s-webui-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - PASETO_SECRET_KEY=dev-32-byte-secret-change-in-production-please
      - TOKEN_EXPIRES_IN=24h
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://k8s_user:k8s_password@postgres:5432/k8s_webui
      - K8S_NAMESPACE=base-infrastructure
    volumes:
      - ~/.kube:/root/.kube:ro  # Mount kubeconfig for development
      - ./backend/src:/app/src:ro  # For hot reload in development
    depends_on:
      - redis
      - postgres
    networks:
      - k8s-webui-network

  # Frontend Svelte application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: k8s-webui-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src:ro  # For hot reload in development
    depends_on:
      - backend
    networks:
      - k8s-webui-network

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: k8s-webui-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - k8s-webui-network

  # PostgreSQL for audit logs and application data
  postgres:
    image: postgres:15
    container_name: k8s-webui-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=k8s_webui
      - POSTGRES_USER=k8s_user
      - POSTGRES_PASSWORD=k8s_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - k8s-webui-network

volumes:
  redis-data:
    name: k8s-webui-redis-data
  postgres-data:
    name: k8s-webui-postgres-data

networks:
  k8s-webui-network:
    name: k8s-webui-network
    driver: bridge