name: Build and Push Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: git.arcbjorn.com
        username: ${{ gitea.actor }}
        password: ${{ secrets.RUNNER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          git.arcbjorn.com/${{ gitea.repository }}:${{ gitea.sha }}
          git.arcbjorn.com/${{ gitea.repository }}:latest