name: Build and Deploy K8s WebUI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: git.arcbjorn.com  # Change to docker.io for Docker Hub
  IMAGE_NAME_BACKEND: k8s-webui-backend
  IMAGE_NAME_FRONTEND: k8s-webui-frontend

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Extract metadata
      id: meta
      run: |
        echo "date=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        echo "sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_BACKEND }}:latest
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_BACKEND }}:${{ steps.meta.outputs.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_FRONTEND }}:latest
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.meta.outputs.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Kubernetes manifests
      run: |
        # Update image tags in deployment files
        sed -i "s|image: k8s-webui-backend:latest|image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_BACKEND }}:${{ steps.meta.outputs.sha }}|g" ../base_infrastructure/k8s/k8s-webui/backend-deployment.yaml
        sed -i "s|image: k8s-webui-frontend:latest|image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.meta.outputs.sha }}|g" ../base_infrastructure/k8s/k8s-webui/frontend-deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        cd ../base_infrastructure/k8s/k8s-webui
        chmod +x deploy.sh
        ./deploy.sh

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/k8s-webui-backend -n k8s-webui --timeout=300s
        kubectl rollout status deployment/k8s-webui-frontend -n k8s-webui --timeout=300s
        kubectl get pods -n k8s-webui